/**
 * AUTO-GENERATED by `/hub/email-builder` — do not edit by hand.
 * Hand-edits will be overwritten on the next save from the builder UI.
 */
import * as React from "react";

import { Barebone } from "../../../core/email/layouts/Barebone.js";
import { CTA, Footer, Greeting, Paragraph } from "../../../core/email/blocks/index.js";
import type { BrandConfig } from "../../../core/email/brand.js";

export interface NewDeviceVars {
  appName: string;
  deviceLabel: string;
  ipAddress: string;
  location: string;
  recipientName: string;
  revokeUrl: string;
  signedInAt: string;
}

export const newDeviceMeta = {
  name: "new-device",
  subject: (vars: NewDeviceVars): string => `New sign-in to ${vars.appName}`,
};

export interface NewDeviceProps extends NewDeviceVars {
  brand?: BrandConfig;
}

export default function NewDevice(props: NewDeviceProps): React.ReactElement {
  return (
    <Barebone
      brand={props.brand}
      preheader={`A new device just signed in to your ${props.appName} account`}
    >
      <Greeting brand={props.brand}>Hello {props.recipientName},</Greeting>
      <Paragraph brand={props.brand}>
        We noticed a new sign-in to your {props.appName} account. If this was you, no further action
        is needed.
      </Paragraph>
      <Paragraph brand={props.brand}>Device: {props.deviceLabel}</Paragraph>
      <Paragraph brand={props.brand}>Location: {props.location}</Paragraph>
      <Paragraph brand={props.brand}>IP address: {props.ipAddress}</Paragraph>
      <Paragraph brand={props.brand}>Time: {props.signedInAt}</Paragraph>
      <Paragraph brand={props.brand}>
        If you did not sign in, revoke this session immediately and change your password.
      </Paragraph>
      <CTA brand={props.brand} href={props.revokeUrl}>
        Review devices
      </CTA>
      <Footer brand={props.brand}>
        Location is approximate (city / country only). We never store the precise coordinates of
        your sign-in.
      </Footer>
    </Barebone>
  );
}
