/**
 * OpenAPI 3.1 components for RFC 7807 problem-details
 *.
 *
 * Pure builder. The Swagger boot wires the result into the
 * generated OpenAPI document so every route can `$ref` the same
 * problem-details schema for its 4xx/5xx responses.
 *
 * The `code` enum is the union of `CORE_ERROR_CODES` and the
 * project's own `APP_*` codes; sorted alphabetically + deduped so
 * the rendered OpenAPI document is byte-deterministic across
 * re-runs (CI snapshot-friendly).
 */

const CODE_RE = /^[A-Z][A-Z0-9_]+$/;

export interface OpenApiProblemSchemasInput {
  coreCodes: string[];
  appCodes: string[];
}

export interface OpenApiSchema {
  type: string;
  required?: string[];
  properties: Record<string, OpenApiPropertySchema>;
}

export interface OpenApiPropertySchema {
  type?: string;
  enum?: string[];
  minimum?: number;
  maximum?: number;
  description?: string;
  format?: string;
}

export interface OpenApiResponse {
  description: string;
  content: Record<string, { schema: { $ref: string } }>;
}

export interface OpenApiProblemDetailsComponents {
  components: {
    schemas: { ProblemDetails: OpenApiSchema };
    responses: { ProblemDetailsResponse: OpenApiResponse };
  };
}

export function buildProblemDetailsOpenApiComponents(
  input: OpenApiProblemSchemasInput,
): OpenApiProblemDetailsComponents {
  for (const code of [...input.coreCodes, ...input.appCodes]) {
    if (!CODE_RE.test(code)) {
      throw new Error(`openapi-problem-schemas: code "${code}" must match ${CODE_RE}`);
    }
  }
  const codeEnum = [...new Set([...input.coreCodes, ...input.appCodes])].sort();

  return {
    components: {
      schemas: {
        ProblemDetails: {
          type: "object",
          required: ["type", "title", "status", "code"],
          properties: {
            type: {
              type: "string",
              format: "uri",
              description: "Problem-type URI (RFC 7807 §3.1).",
            },
            title: {
              type: "string",
              description: "Short, human-readable summary of the problem type.",
            },
            status: {
              type: "integer",
              minimum: 100,
              maximum: 599,
              description: "HTTP status code generated by the origin server.",
            },
            code: {
              type: "string",
              enum: codeEnum,
              description: "Stable machine-readable identifier (CORE_* or APP_* prefix).",
            },
            detail: {
              type: "string",
              description: "Human-readable explanation specific to this occurrence.",
            },
            instance: {
              type: "string",
              description: "URI reference identifying the specific occurrence.",
            },
          },
        },
      },
      responses: {
        ProblemDetailsResponse: {
          description: "RFC 7807 problem-details payload.",
          content: {
            "application/problem+json": {
              schema: { $ref: "#/components/schemas/ProblemDetails" },
            },
          },
        },
      },
    },
  };
}
