/**
 * @Searchable + Migration-Generator (PLAN.md §11 + §32 Phase 5).
 *
 * Decorator stamps a per-class metadata table that the migration
 * generator walks to emit:
 *   - a `search tsvector` column on the resource's Postgres table
 *   - a GIN index over that column
 *   - a trigger function that recomputes the column on insert/update
 *   - a trigger that calls the function
 */

const SEARCHABLE_FIELDS = Symbol.for('core.search.searchable-fields');
const VALID_WEIGHTS = new Set<string>(['A', 'B', 'C', 'D']);
const SAFE_IDENT = /^[a-z_][a-z0-9_]*$/i;

export type SearchWeight = 'A' | 'B' | 'C' | 'D';

export interface SearchableField {
  field: string;
  weight: SearchWeight;
}

export interface SearchableOptions {
  weight?: SearchWeight;
}

interface MetadataTarget {
  [SEARCHABLE_FIELDS]?: SearchableField[];
}

/**
 * Legacy property decorator: attaches the field name + weight to the
 * class' constructor metadata. We use the legacy form (not Stage 3)
 * because `experimentalDecorators=true` is on for NestJS, and Stage 3
 * accessor decorators are not available under that flag.
 */
export function Searchable(options: SearchableOptions = {}): PropertyDecorator {
  const weight = options.weight ?? 'D';
  if (!VALID_WEIGHTS.has(weight)) {
    throw new Error(`@Searchable: invalid weight "${weight}" (allowed: A,B,C,D)`);
  }
  return (target, propertyKey) => {
    if (typeof propertyKey !== 'string') return;
    const ctor = target.constructor as MetadataTarget;
    const list = ctor[SEARCHABLE_FIELDS] ?? [];
    if (!list.some((f) => f.field === propertyKey)) {
      list.push({ field: propertyKey, weight });
    }
    ctor[SEARCHABLE_FIELDS] = list;
  };
}

export function getSearchableFields(ctor: { new (...args: unknown[]): unknown }): SearchableField[] {
  return ((ctor as MetadataTarget)[SEARCHABLE_FIELDS] ?? []).slice();
}

export class SearchableRegistry {
  private readonly entries = new Map<string, { ctor: Function; fields: SearchableField[] }>();

  register(table: string, ctor: Function, fields: SearchableField[]): void {
    if (fields.length === 0) {
      throw new Error('SearchableRegistry: fields list must not be empty');
    }
    if (this.entries.has(table)) {
      throw new Error(`SearchableRegistry: duplicate table "${table}"`);
    }
    this.entries.set(table, { ctor, fields });
  }

  listResources(): string[] {
    return [...this.entries.keys()].sort();
  }
}

/**
 * Emit the SQL for a single resource's tsvector column + index +
 * trigger. Identifiers are validated against `[a-z_][a-z0-9_]*` to
 * ensure injection safety; project-controlled config strings should
 * normally be safe but the guard catches typos and unsanitized input.
 */
export function generateSearchMigration(table: string, fields: SearchableField[]): string {
  if (!SAFE_IDENT.test(table)) {
    throw new Error(`generateSearchMigration: invalid table identifier "${table}"`);
  }
  for (const { field } of fields) {
    if (!SAFE_IDENT.test(field)) {
      throw new Error(`generateSearchMigration: invalid field identifier "${field}"`);
    }
  }

  const setweightClauses = fields
    .map(({ field, weight }) => `setweight(to_tsvector('simple', coalesce(NEW.${field}, '')), '${weight}')`)
    .join(' || ');

  const fnName = `${table}_search_trigger`;
  const triggerName = `${table}_search_trigger`;

  return `-- Auto-generated by generateSearchMigration() — do not edit by hand.
ALTER TABLE ${table} ADD COLUMN search tsvector;

CREATE INDEX ${table}_search_idx ON ${table} USING GIN (search);

CREATE FUNCTION ${fnName}() RETURNS trigger AS $$
BEGIN
  NEW.search := ${setweightClauses};
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER ${triggerName}
BEFORE INSERT OR UPDATE ON ${table}
FOR EACH ROW EXECUTE FUNCTION ${fnName}();
`;
}
