import { describe, expect, it } from "vitest";

import {
  planEnsurePrismaClient,
  type PrismaClientCheckLayout,
} from "../../src/core/testing/ensure-prisma-client.js";

/**
 * Story · ensure-prisma-client (test infra).
 *
 * Why this exists: a pristine `lt fullstack init --next` workspace
 * walks through `bun install → bun run setup → docker compose up -d
 * postgres → bun run prepare:schema → bun run prisma:migrate → bun
 * run test:e2e`. None of those steps run `prisma generate`. The
 * postinstall hook only writes the pnpm-hoisting symlink — it bails
 * out with "package-output-missing" when the generator hasn't run
 * yet — and `prisma migrate deploy` does not generate a client either.
 *
 * Result: the very first `bun run test:e2e` after a fresh init fails
 * with `Error: Cannot find module '.prisma/client/default'` because
 * `@prisma/client/default.js` does `require('.prisma/client/default')`
 * and that file was never written.
 *
 * This planner is the pure half of the fix. The runner (in
 * `tests/global-setup.ts`) executes the `generate` plan via
 * `bunx prisma generate` so a fresh checkout's `bun run test:e2e`
 * boots the same way it does on a repo where the developer ran
 * `prisma generate` by hand.
 */
describe("Story · ensure-prisma-client planner", () => {
  function layout(overrides: Partial<PrismaClientCheckLayout> = {}): PrismaClientCheckLayout {
    return {
      packageRoot: "/ws/projects/api",
      packagePrismaClientDefaultExists: false,
      schemaExists: true,
      ...overrides,
    };
  }

  it("plans `bunx prisma generate` when the client is missing", () => {
    const plan = planEnsurePrismaClient(layout());
    expect(plan).toEqual({
      kind: "generate",
      command: "bunx",
      args: ["prisma", "generate"],
      cwd: "/ws/projects/api",
    });
  });

  it("skips when the generator output already exists", () => {
    // Idempotent — re-running test infra after the client was
    // generated by `bun run prisma:generate` (or by a previous test
    // run) must not pay the regeneration tax.
    const plan = planEnsurePrismaClient(layout({ packagePrismaClientDefaultExists: true }));
    expect(plan).toEqual({ kind: "skip", reason: "client-already-exists" });
  });

  it("skips when the prisma schema is missing", () => {
    // Defensive: an unusual layout (e.g. a sub-package without its own
    // schema) must not invoke `prisma generate` against a non-existent
    // schema and crash the whole test runner.
    const plan = planEnsurePrismaClient(
      layout({ schemaExists: false, packagePrismaClientDefaultExists: false }),
    );
    expect(plan).toEqual({ kind: "skip", reason: "no-schema" });
  });

  it("the plan's cwd matches the supplied package root", () => {
    // `prisma generate` reads `prisma/schema.prisma` relative to its
    // cwd; running it from the repo root would either pick up a
    // wrong schema or fail with "schema not found". Pin the cwd
    // contract so a future refactor can't lose it.
    const plan = planEnsurePrismaClient(layout({ packageRoot: "/elsewhere/api" }));
    if (plan.kind !== "generate") throw new Error("unexpected plan");
    expect(plan.cwd).toBe("/elsewhere/api");
  });
});
