import { describe, expect, it } from "vitest";

import { FeaturesSchema } from "../../src/core/features/features.js";
import { concatenateSchema, type SchemaConcatInput } from "../../src/core/setup/schema-concat.js";

/**
 * Story · Schema-Concat.
 *
 * Pure planner: features + schema sources → concatenated schema string
 * + included-feature list. The CLI script reads core / feature
 * `.prisma` files from disk and writes the result to
 * `prisma/schema.generated.prisma`; the planner stays I/O-free so it's
 * unit-testable and fully deterministic.
 *
 * Layout:
 *   prisma/schema.prisma           (core, always present)
 *   prisma/features/<f>.prisma     (loaded only if features.<f>.enabled)
 */
describe("Story · Schema-Concat planner", () => {
  function input(overrides: Partial<SchemaConcatInput> = {}): SchemaConcatInput {
    return {
      coreSchema: "model User { id String @id }",
      featureSchemas: {},
      features: FeaturesSchema.parse({}),
      ...overrides,
    };
  }

  it("returns only the core schema when no toggleable feature is enabled", () => {
    const result = concatenateSchema(
      input({
        features: FeaturesSchema.parse({
          webhooks: { enabled: false },
          search: { enabled: false },
          mcp: { enabled: false },
          geo: { enabled: false },
          powerSync: { enabled: false },
          realtime: { enabled: false },
          fieldEncryption: { enabled: false },
        }),
      }),
    );
    expect(result.includedFeatures).toEqual([]);
    expect(result.schema).toContain("model User");
  });

  it("appends the webhooks feature schema when enabled", () => {
    const result = concatenateSchema(
      input({
        featureSchemas: { webhooks: "model Webhook { id String @id }" },
        features: FeaturesSchema.parse({ webhooks: { enabled: true } }),
      }),
    );
    expect(result.includedFeatures).toContain("webhooks");
    expect(result.schema).toContain("model Webhook");
  });

  it("appends multiple feature schemas in deterministic alphabetical order", () => {
    const result = concatenateSchema(
      input({
        featureSchemas: {
          webhooks: "model Webhook { id String @id }",
          geo: "model Geo { id String @id }",
          search: "model Search { id String @id }",
        },
        features: FeaturesSchema.parse({
          webhooks: { enabled: true },
          geo: { enabled: true, provider: "nominatim" },
          search: { enabled: true },
        }),
      }),
    );
    expect(result.includedFeatures).toEqual(["geo", "search", "webhooks"]);
    const geoIndex = result.schema.indexOf("model Geo");
    const searchIndex = result.schema.indexOf("model Search");
    const webhookIndex = result.schema.indexOf("model Webhook");
    expect(geoIndex).toBeGreaterThan(0);
    expect(geoIndex).toBeLessThan(searchIndex);
    expect(searchIndex).toBeLessThan(webhookIndex);
  });

  it("skips a feature whose schema source is absent", () => {
    const result = concatenateSchema(
      input({
        featureSchemas: {},
        features: FeaturesSchema.parse({ webhooks: { enabled: false } }),
      }),
    );
    expect(result.includedFeatures).toEqual([]);
  });

  it("treats enabled-but-no-schema features as runtime-only (skipped, not thrown)", () => {
    // Some toggleable features (mcp, realtime, fieldEncryption,
    // webhooks-in-core) have no `prisma/features/<name>.prisma` file
    // because they're runtime-only or share the core schema. We
    // silently skip them and surface them via `skippedFeatures` so
    // tooling can show the user what got skipped.
    const result = concatenateSchema(
      input({
        featureSchemas: {},
        features: FeaturesSchema.parse({ fieldEncryption: { enabled: true } }),
      }),
    );
    expect(result.includedFeatures).toEqual([]);
    expect(result.skippedFeatures).toContain("fieldEncryption");
  });

  it("emits a generated-by header so manual edits get noticed", () => {
    const result = concatenateSchema(input());
    expect(result.schema).toMatch(/^\/\/ Generated by prepare-schema/);
  });

  it("is idempotent for identical inputs", () => {
    const features = FeaturesSchema.parse({
      webhooks: { enabled: true },
      search: { enabled: true },
    });
    const featureSchemas = {
      webhooks: "model Webhook { id String @id }",
      search: "model Search { id String @id }",
    };
    const a = concatenateSchema(input({ features, featureSchemas }));
    const b = concatenateSchema(input({ features, featureSchemas }));
    expect(a.schema).toBe(b.schema);
  });

  it("separates the core and each feature schema with section banners", () => {
    const result = concatenateSchema(
      input({
        featureSchemas: { webhooks: "model Webhook { id String @id }" },
        features: FeaturesSchema.parse({ webhooks: { enabled: true } }),
      }),
    );
    expect(result.schema).toMatch(/\/\/ ─+ core ─+/);
    expect(result.schema).toMatch(/\/\/ ─+ feature: webhooks ─+/);
  });

  it("reflects all toggleable features (webhooks, search, mcp, geo, powerSync, realtime, fieldEncryption)", () => {
    const featureSchemas = {
      webhooks: "model A { id String @id }",
      search: "model B { id String @id }",
      mcp: "model C { id String @id }",
      geo: "model D { id String @id }",
      powerSync: "model E { id String @id }",
      realtime: "model F { id String @id }",
      fieldEncryption: "model G { id String @id }",
    };
    const result = concatenateSchema(
      input({
        featureSchemas,
        features: FeaturesSchema.parse({
          webhooks: { enabled: true },
          search: { enabled: true },
          mcp: { enabled: true },
          geo: { enabled: true, provider: "nominatim" },
          powerSync: { enabled: true },
          realtime: { enabled: true },
          fieldEncryption: { enabled: true },
        }),
      }),
    );
    expect(result.includedFeatures.sort()).toEqual([
      "fieldEncryption",
      "geo",
      "mcp",
      "powerSync",
      "realtime",
      "search",
      "webhooks",
    ]);
  });
});
