import type { Features } from "../features/features.js";

/**
 * Schema-Concat planner (PLAN.md §19.4 Approach B + §32 Phase 7).
 *
 * Pure function: takes the core Prisma schema, a map of per-feature
 * schemas, and the resolved Features object; returns a single
 * concatenated schema string and the list of included features.
 *
 * The CLI script reads `prisma/schema.prisma` + `prisma/features/*`
 * from disk, calls this planner, and writes the result to
 * `prisma/schema.generated.prisma`. By keeping the planner I/O-free
 * we get:
 *
 *   1. Deterministic output. Same inputs → byte-identical schema.
 *   2. Test coverage. No fs mocks needed.
 *   3. Reusable. The wizard's runner and a `prisma generate` hook
 *      can both call it.
 *
 * Order matters for prisma — but only between models that reference
 * each other. We sort feature blocks alphabetically so the diff stays
 * readable across feature toggles.
 */

const TOGGLEABLE_FEATURES = [
  "webhooks",
  "search",
  "mcp",
  "geo",
  "powerSync",
  "realtime",
  "fieldEncryption",
] as const;

type ToggleableFeature = (typeof TOGGLEABLE_FEATURES)[number];

export interface SchemaConcatInput {
  coreSchema: string;
  featureSchemas: Partial<Record<ToggleableFeature, string>>;
  features: Features;
}

export interface SchemaConcatOutput {
  schema: string;
  includedFeatures: ToggleableFeature[];
}

export class MissingFeatureSchemaError extends Error {
  constructor(feature: string) {
    super(`schema-concat: feature "${feature}" is enabled but no schema source was provided`);
    this.name = "MissingFeatureSchemaError";
  }
}

export function concatenateSchema(input: SchemaConcatInput): SchemaConcatOutput {
  const enabled = TOGGLEABLE_FEATURES.filter((feature) =>
    isEnabled(input.features, feature),
  ).sort();

  for (const feature of enabled) {
    if (!input.featureSchemas[feature]) {
      throw new MissingFeatureSchemaError(feature);
    }
  }

  const sections: string[] = [];
  sections.push("// Generated by prepare-schema. Do not edit by hand.");
  sections.push("// Run `bun run prepare:schema` to regenerate.");
  sections.push("");
  sections.push(banner("core"));
  sections.push(input.coreSchema.trim());

  for (const feature of enabled) {
    sections.push("");
    sections.push(banner(`feature: ${feature}`));
    sections.push((input.featureSchemas[feature] ?? "").trim());
  }

  return {
    schema: sections.join("\n") + "\n",
    includedFeatures: enabled,
  };
}

function isEnabled(features: Features, feature: ToggleableFeature): boolean {
  const block = features[feature] as { enabled?: boolean } | undefined;
  return block?.enabled === true;
}

function banner(label: string): string {
  return `// ──────────── ${label} ────────────`;
}
