import { type Features, FeaturesSchema } from '../features/features.js';

/**
 * Setup-Wizard planner (PLAN.md §19.5 + §32 Phase 7).
 *
 * Pure function: WizardAnswers → WizardOutcome. The CLI prompt loop
 * (next slice) collects answers, the planner produces the exact bytes
 * to write to disk, and a runner executes the writes. Three benefits
 * fall out of the split:
 *
 *   1. Idempotent. Same answers → same files; re-runs are safe.
 *   2. Test-friendly. No I/O, no prompts, no sleeps.
 *   3. Reviewable. The diff tells you what the wizard changed without
 *      having to replay the questions.
 *
 * The outcome contains:
 *   - `features`       parsed Features object (post-default merge)
 *   - `envExample`     deterministic .env content
 *   - `featuresSource` TypeScript source for src/config/features.ts
 *     that imports FeaturesSchema and exports a typed const.
 */

export type EmailProvider = 'smtp' | 'brevo';

export interface WizardAnswers {
  projectName: string;
  multiTenant: boolean;
  /** Enables PowerSync for offline-first mobile clients (PLAN.md §13). */
  mobile: boolean;
  webhooks: boolean;
  search: boolean;
  mcp: boolean;
  fieldEncryption: boolean;
  realtime: boolean;
  emailEnabled: boolean;
  emailProvider: EmailProvider;
}

export interface WizardOutcome {
  features: Features;
  envExample: string;
  featuresSource: string;
}

export function planSetup(answers: WizardAnswers): WizardOutcome {
  if (!answers.projectName) {
    throw new Error('setup-wizard: projectName must be a non-empty string');
  }

  const features = FeaturesSchema.parse({
    multiTenancy: { enabled: answers.multiTenant },
    powerSync: { enabled: answers.mobile },
    webhooks: { enabled: answers.webhooks },
    search: { enabled: answers.search },
    mcp: { enabled: answers.mcp },
    fieldEncryption: { enabled: answers.fieldEncryption },
    realtime: { enabled: answers.realtime },
    email: { enabled: answers.emailEnabled, provider: answers.emailProvider },
  });

  return {
    features,
    envExample: renderEnvExample(answers),
    featuresSource: renderFeaturesSource(answers),
  };
}

function renderEnvExample(answers: WizardAnswers): string {
  const lines: string[] = [];
  lines.push(`# ${answers.projectName} — generated by setup-wizard`);
  lines.push('# Copy this file to `.env` and fill in the placeholder secrets.');
  lines.push('# `bun run setup` will copy + auto-generate strong secrets for you.');
  lines.push('');
  lines.push('# ── Server boot ────────────────────────────────────────────────');
  lines.push('NODE_ENV=development');
  lines.push('PORT=3000');
  lines.push('HOST=0.0.0.0');
  lines.push('APP_BASE_URL=http://localhost:3000');
  lines.push('# Where your problem-details `type` URLs resolve to (RFC 7807).');
  lines.push('ERROR_DOC_BASE_URL=https://errors.example.com');
  lines.push('');
  lines.push('# ── Database (Postgres + docker-compose interpolation) ────────');
  lines.push(`POSTGRES_USER=${answers.projectName}`);
  lines.push('POSTGRES_PASSWORD=change-me-strong-pass');
  lines.push(`POSTGRES_DB=${answers.projectName}`);
  lines.push(
    `DATABASE_URL=postgresql://${answers.projectName}:change-me-strong-pass@localhost:5432/${answers.projectName}`,
  );
  lines.push('');
  lines.push('# ── Auth (Better-Auth) ─────────────────────────────────────────');
  lines.push('BETTER_AUTH_SECRET=change-me-32-chars-minimum-XXXXXX');
  lines.push('');
  lines.push('# ── System bootstrap (matched pair, unset to skip auto-admin) ──');
  lines.push('SYSTEM_SETUP_ADMIN_EMAIL=admin@example.com');
  lines.push('SYSTEM_SETUP_ADMIN_PASSWORD=change-me-12-chars-min');
  lines.push('');
  lines.push('# ── Object storage (RustFS / S3-compatible) ────────────────────');
  lines.push('S3_ACCESS_KEY=rustfs');
  lines.push('S3_SECRET_KEY=rustfs-secret');
  if (answers.multiTenant) {
    lines.push('');
    lines.push('# ── Multi-tenancy ──────────────────────────────────────────────');
    lines.push('TENANT_HEADER=x-tenant-id');
  }
  if (answers.emailEnabled) {
    lines.push('');
    lines.push('# ── Email ──────────────────────────────────────────────────────');
    if (answers.emailProvider === 'smtp') {
      lines.push('SMTP_HOST=localhost');
      lines.push('SMTP_PORT=1025');
      lines.push('SMTP_USER=');
      lines.push('SMTP_PASS=');
    } else {
      lines.push('BREVO_API_KEY=');
    }
  }
  if (answers.fieldEncryption) {
    lines.push('');
    lines.push('# ── Field encryption (32-byte base64 KEK; rotate via versioned tags) ─');
    lines.push('FIELD_ENCRYPTION_KEK=');
  }
  if (answers.mobile) {
    lines.push('');
    lines.push('# ── PowerSync (mobile offline-sync) ────────────────────────────');
    lines.push('POWERSYNC_DB_PASSWORD=change-me-powersync-replication-pass');
    lines.push('POWERSYNC_JWKS_URL=http://host.docker.internal:3000/.well-known/jwks');
    lines.push('POWERSYNC_URL=http://localhost:8080');
    lines.push('POWERSYNC_TOKEN=');
  }
  lines.push('');
  lines.push('# ── Observability (optional) ───────────────────────────────────');
  lines.push('# OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development');
  return lines.join('\n') + '\n';
}

function renderFeaturesSource(answers: WizardAnswers): string {
  return [
    `// Generated by setup-wizard for "${answers.projectName}".`,
    "// Edit feature flags here; the schema enforces the shape at boot.",
    '',
    "import { FeaturesSchema } from '../core/features/features.js';",
    '',
    'export const features = FeaturesSchema.parse({',
    `  multiTenancy: { enabled: ${answers.multiTenant} },`,
    `  email: { enabled: ${answers.emailEnabled}, provider: ${quote(answers.emailProvider)} },`,
    `  powerSync: { enabled: ${answers.mobile} },`,
    `  webhooks: { enabled: ${answers.webhooks} },`,
    `  search: { enabled: ${answers.search} },`,
    `  mcp: { enabled: ${answers.mcp} },`,
    `  fieldEncryption: { enabled: ${answers.fieldEncryption} },`,
    `  realtime: { enabled: ${answers.realtime} },`,
    '});',
    '',
  ].join('\n');
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
