import { type Features, FeaturesSchema } from "../features/features.js";

/**
 * Setup-Wizard planner.
 *
 * Pure function: WizardAnswers → WizardOutcome. The CLI prompt loop
 * (next slice) collects answers, the planner produces the exact bytes
 * to write to disk, and a runner executes the writes. Three benefits
 * fall out of the split:
 *
 *   1. Idempotent. Same answers → same files; re-runs are safe.
 *   2. Test-friendly. No I/O, no prompts, no sleeps.
 *   3. Reviewable. The diff tells you what the wizard changed without
 *      having to replay the questions.
 *
 * The outcome contains:
 *   - `features`       parsed Features object (post-default merge)
 *   - `envExample`     deterministic .env content
 *   - `featuresSource` TypeScript source for src/config/features.ts
 *     that imports FeaturesSchema and exports a typed const.
 */

export type EmailProvider = "smtp" | "brevo";

export interface WizardAnswers {
  projectName: string;
  multiTenant: boolean;
  /** Enables PowerSync for offline-first mobile clients. */
  mobile: boolean;
  webhooks: boolean;
  search: boolean;
  mcp: boolean;
  fieldEncryption: boolean;
  realtime: boolean;
  emailEnabled: boolean;
  emailProvider: EmailProvider;
  /**
   * Host port that Compose will bind Postgres on. Two `--next`
   * workspaces on the same machine cannot share the default `5432:5432`
   * binding — the second `docker compose up` fails with EADDRINUSE.
   * The runner detects a free port at setup time and passes it here;
   * the resulting `.env` writes both `POSTGRES_HOST_PORT=<port>` and a
   * `DATABASE_URL=…@localhost:<port>/…` baked with the same number.
   * Defaults to 5432 when unset (e.g. the regression-test fixture).
   */
  postgresHostPort?: number;
}

export interface WizardOutcome {
  features: Features;
  envExample: string;
  featuresSource: string;
}

/**
 * `buildDefaultEnvExample()` — emits the all-features-on `.env.example`
 * the repo commits. Runners (and the regression test) call this so the
 * committed file is regenerable from a single source of truth.
 */
export function buildDefaultEnvExample(): string {
  return planSetup({
    projectName: "nest-base",
    multiTenant: true,
    mobile: true,
    webhooks: true,
    search: true,
    mcp: true,
    fieldEncryption: true,
    realtime: true,
    emailEnabled: true,
    emailProvider: "smtp",
  }).envExample;
}

export function planSetup(answers: WizardAnswers): WizardOutcome {
  if (!answers.projectName) {
    throw new Error("setup-wizard: projectName must be a non-empty string");
  }

  const features = FeaturesSchema.parse({
    multiTenancy: { enabled: answers.multiTenant },
    powerSync: { enabled: answers.mobile },
    webhooks: { enabled: answers.webhooks },
    search: { enabled: answers.search },
    mcp: { enabled: answers.mcp },
    fieldEncryption: { enabled: answers.fieldEncryption },
    realtime: { enabled: answers.realtime },
    email: { enabled: answers.emailEnabled, provider: answers.emailProvider },
  });

  return {
    features,
    envExample: renderEnvExample(answers),
    featuresSource: renderFeaturesSource(answers),
  };
}

function renderEnvExample(answers: WizardAnswers): string {
  const lines: string[] = [];
  lines.push(`# ${answers.projectName} — generated by setup-wizard`);
  lines.push("# Copy this file to `.env` and fill in the sample secrets.");
  lines.push("# `bun run setup` will copy + auto-generate strong secrets for you.");
  lines.push("");
  lines.push("# ── Server boot ────────────────────────────────────────────────");
  lines.push("NODE_ENV=development");
  lines.push("PORT=3000");
  lines.push("HOST=0.0.0.0");
  // Portless serves the API at <api>.<project>.localhost with auto-HTTPS.
  // Devs running without portless (DISABLE_PORTLESS=1) edit this back to
  // http://localhost:<port> after `bun run setup`.
  lines.push(`APP_BASE_URL=https://api.${answers.projectName}.localhost`);
  lines.push("# Where your problem-details `type` URLs resolve to (RFC 7807).");
  lines.push("ERROR_DOC_BASE_URL=https://errors.example.com");
  lines.push("");
  const port = answers.postgresHostPort ?? 5432;
  lines.push("# ── Database (Postgres + docker-compose interpolation) ────────");
  lines.push(`POSTGRES_USER=${answers.projectName}`);
  lines.push("POSTGRES_PASSWORD=change-me-strong-pass");
  lines.push(`POSTGRES_DB=${answers.projectName}`);
  lines.push(
    `DATABASE_URL=postgresql://${answers.projectName}:change-me-strong-pass@localhost:${port}/${answers.projectName}`,
  );
  lines.push("");
  lines.push("# ── Docker Compose ────────────────────────────────────────────");
  // Pin the Compose project name so each workspace gets its own
  // `<name>_postgres_data` volume — without this, Compose derives the
  // project name from the parent dir of `docker-compose.yml`, which is
  // always `api` (since the file lives at `projects/api/`). Two `--next`
  // workspaces then share the same volume and inherit each other's
  // POSTGRES_PASSWORD on first boot, surfacing as P1000 auth errors.
  lines.push(`COMPOSE_PROJECT_NAME=${answers.projectName}`);
  // Host-port Postgres is bound on. Two workspaces on the same machine
  // collide on 5432 unless one of them shifts. The runner picks the
  // first free port via `findFreePostgresPort()`; flip manually here
  // (and the port in DATABASE_URL above) if you need a specific value.
  lines.push(`POSTGRES_HOST_PORT=${port}`);
  lines.push("");
  lines.push("# ── Auth (Better-Auth) ─────────────────────────────────────────");
  lines.push("BETTER_AUTH_SECRET=change-me-32-chars-minimum-XXXXXX");
  lines.push("# Rate-limiter for /api/auth/* routes (credential-stuffing protection).");
  lines.push("# Defaults to false in test/development (rapid runs exhaust the window),");
  lines.push("# true in production. Set explicitly to override the NODE_ENV default.");
  lines.push("# BETTER_AUTH_RATE_LIMIT_ENABLED=false");
  lines.push("");
  lines.push("# ── System bootstrap (matched pair, unset to skip auto-admin) ──");
  lines.push("SYSTEM_SETUP_ADMIN_EMAIL=admin@example.com");
  lines.push("SYSTEM_SETUP_ADMIN_PASSWORD=change-me-12-chars-min");
  lines.push("");
  lines.push("# ── Object storage (RustFS / S3-compatible) ────────────────────");
  lines.push("S3_ACCESS_KEY=rustfs");
  lines.push("S3_SECRET_KEY=rustfs-secret");
  if (answers.multiTenant) {
    lines.push("");
    lines.push("# ── Multi-tenancy ──────────────────────────────────────────────");
    lines.push("TENANT_HEADER=x-tenant-id");
  }
  if (answers.emailEnabled) {
    lines.push("");
    lines.push("# ── Email ──────────────────────────────────────────────────────");
    lines.push("# Default points at the Mailpit container in docker-compose");
    lines.push("# (`docker compose up -d mailpit`, web UI on http://localhost:8025).");
    lines.push("# For production, set SMTP_HOST/PORT/USER/PASS to your real relay or");
    lines.push("# switch the provider to Brevo via FEATURE_EMAIL_PROVIDER=brevo.");
    lines.push("SMTP_HOST=localhost");
    lines.push("SMTP_PORT=1025");
    lines.push("SMTP_USER=");
    lines.push("SMTP_PASS=");
    lines.push("# Sender address for outbound mail. Override per environment.");
    lines.push("SMTP_FROM=no-reply@example.com");
    lines.push("# Implicit-TLS (port 465). Leave false for STARTTLS (587) or plain dev.");
    lines.push("SMTP_SECURE=false");
    lines.push("# Force STARTTLS upgrade on a non-secure port. Off by default so dev");
    lines.push("# relays without TLS (Mailpit) keep working out of the box.");
    lines.push("SMTP_REQUIRE_TLS=false");
    lines.push("# Outbound connection pool size + per-attempt timeout (ms). Outbox");
    lines.push("# (#11) handles retries; the driver itself fails fast.");
    lines.push("SMTP_POOL_SIZE=5");
    lines.push("SMTP_TIMEOUT_MS=10000");
    lines.push("");
    lines.push("# Brevo (transactional API). Required when FEATURE_EMAIL_PROVIDER=brevo");
    lines.push("# OR when you want to use sendTemplate({ brevoTemplateId }) alongside SMTP.");
    lines.push("# Get a key at https://app.brevo.com/settings/keys/api.");
    lines.push("BREVO_API_KEY=");
  }
  if (answers.fieldEncryption) {
    lines.push("");
    lines.push("# ── Field encryption (32-byte base64 KEK; rotate via versioned tags) ─");
    lines.push("FIELD_ENCRYPTION_KEK=");
    lines.push("");
    lines.push("# Comma-separated base64-encoded 32-byte KEKs the multi-KEK extension");
    lines.push("# tries on decrypt-failure (read-side fallback during rotation). On");
    lines.push("# rotation: move the prior FIELD_ENCRYPTION_KEK value into this slot,");
    lines.push("# set the new KEK as primary; existing rows decrypt via legacy");
    lines.push("# fallback without a re-encryption pass. Order matters — list the");
    lines.push("# most-recent legacy first (highest hit rate).");
    lines.push("FIELD_ENCRYPTION_LEGACY_KEKS=");
  }
  if (answers.mobile) {
    lines.push("");
    lines.push("# ── PowerSync (mobile offline-sync) ────────────────────────────");
    lines.push("POWERSYNC_DB_PASSWORD=change-me-powersync-replication-pass");
    lines.push("POWERSYNC_JWKS_URL=http://host.docker.internal:3000/.well-known/jwks");
    lines.push("POWERSYNC_URL=http://localhost:8080");
    lines.push("POWERSYNC_TOKEN=");
  }
  lines.push("");
  lines.push("# ── Observability (optional) ───────────────────────────────────");
  lines.push("# OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development");
  lines.push("");
  lines.push("# ── Feature flags ──────────────────────────────────────────────");
  lines.push("# Override schema defaults from src/core/features/features.ts.");
  lines.push("# Uncomment + edit a line to toggle. Booleans accept");
  lines.push("# true/false/1/0/yes/no/on/off (case-insensitive); arrays are");
  lines.push('# comma-separated. See README "Configuring features".');
  lines.push("");
  lines.push("# Auth methods");
  lines.push("# FEATURE_AUTH_METHODS_EMAIL_PASSWORD=true");
  lines.push("# FEATURE_AUTH_METHODS_TWO_FACTOR=true");
  lines.push("# FEATURE_AUTH_METHODS_PASSKEY=true");
  lines.push("# FEATURE_AUTH_METHODS_API_KEYS=true");
  lines.push("# FEATURE_AUTH_METHODS_SOCIAL_PROVIDERS=");
  lines.push("");
  lines.push("# Multi-tenancy");
  lines.push("# FEATURE_MULTI_TENANCY_ENABLED=true");
  lines.push("# FEATURE_MULTI_TENANCY_RLS=true");
  lines.push("# FEATURE_MULTI_TENANCY_HEADER_NAME=x-tenant-id");
  lines.push("");
  lines.push("# Files (TUS uploads, storage adapter, image transforms)");
  lines.push("# FEATURE_FILES_ENABLED=true");
  lines.push("# FEATURE_FILES_STORAGE_DEFAULT=local");
  lines.push("# FEATURE_FILES_TUS=true");
  lines.push("# FEATURE_FILES_TRANSFORMATIONS=true");
  lines.push("");
  lines.push("# ── File storage (origin + cache) ──────────────────────────────");
  lines.push("# Local driver — filesystem under STORAGE_LOCAL_ROOT (default ./data/uploads)");
  lines.push("# STORAGE_LOCAL_ROOT=./data/uploads");
  lines.push(
    "# Public-facing base URL the LocalStorageAdapter signs into (defaults to APP_BASE_URL)",
  );
  lines.push("# STORAGE_BASE_URL=https://api.example.com/files");
  lines.push("# S3 driver — uncomment when FEATURE_FILES_STORAGE_DEFAULT=s3");
  lines.push("# S3_BUCKET=");
  lines.push("# S3_REGION=us-east-1");
  lines.push("# S3_ENDPOINT=");
  lines.push("# S3_FORCE_PATH_STYLE=false");
  lines.push("# S3_MAX_TTL_SECONDS=3600");
  lines.push("");
  lines.push("# ── TUS resumable uploads ──────────────────────────────────────");
  lines.push("# Hard cap per single upload (bytes); default 50MB");
  lines.push("# TUS_MAX_UPLOAD_BYTES=52428800");
  lines.push(
    "# Per-tenant total quota across in-progress uploads (bytes); default unset = no quota",
  );
  lines.push("# TUS_MAX_BYTES_PER_TENANT=");
  lines.push("# Chunk expiration (seconds) — sweeps stale resumable uploads; default 24h");
  lines.push("# TUS_CHUNK_EXPIRATION_SECONDS=86400");
  lines.push("");
  lines.push("# Email");
  lines.push("# FEATURE_EMAIL_ENABLED=true");
  lines.push("# FEATURE_EMAIL_PROVIDER=smtp");
  lines.push("");
  lines.push("# Cross-cutting (default on)");
  lines.push("# FEATURE_RATE_LIMIT_ENABLED=true");
  lines.push("# FEATURE_IDEMPOTENCY_ENABLED=true");
  lines.push("# FEATURE_OBSERVABILITY_ENABLED=true");
  lines.push("# FEATURE_JOBS_ENABLED=true");
  lines.push("");
  lines.push("# Opt-in features (default off)");
  lines.push("# FEATURE_WEBHOOKS_ENABLED=false");
  lines.push("# FEATURE_SEARCH_ENABLED=false");
  lines.push("# FEATURE_REALTIME_ENABLED=false");
  lines.push("# FEATURE_POWERSYNC_ENABLED=false");
  lines.push("# FEATURE_MCP_ENABLED=false");
  lines.push("# FEATURE_FIELD_ENCRYPTION_ENABLED=false");
  lines.push("");
  lines.push("# Geo (PostGIS, geocoding)");
  lines.push("# FEATURE_GEO_ENABLED=false");
  lines.push("# FEATURE_GEO_PROVIDER=nominatim");
  lines.push("");
  lines.push("# GeoIP (offline IP→country/city lookup via .mmdb)");
  lines.push("# Default provider `dbip-lite` is CC-BY-4.0, no key required, monthly snapshot.");
  lines.push("# `bun run scripts/download-geoip.ts` populates `./data/geoip/city.mmdb`.");
  lines.push("# FEATURE_GEO_IP_ENABLED=false");
  lines.push("# FEATURE_GEO_IP_PROVIDER=dbip-lite");
  lines.push("# FEATURE_GEO_IP_DB_PATH=./data/geoip/city.mmdb");
  lines.push("#");
  lines.push("# Opt-in: MaxMind GeoLite2-City for higher accuracy + weekly updates.");
  lines.push("# Free signup at https://www.maxmind.com/en/geolite2/signup. NB: every");
  lines.push("# download leaks the caller's IP to MaxMind — pick `dbip-lite` for");
  lines.push("# Schrems-II-strict setups.");
  lines.push("# FEATURE_GEO_IP_PROVIDER=maxmind");
  lines.push("# FEATURE_GEO_IP_LICENSE_KEY=");
  return lines.join("\n") + "\n";
}

function renderFeaturesSource(answers: WizardAnswers): string {
  return [
    `// Generated by setup-wizard for "${answers.projectName}".`,
    "// Edit feature flags here; the schema enforces the shape at boot.",
    "",
    "import { FeaturesSchema } from '../core/features/features.js';",
    "",
    "export const features = FeaturesSchema.parse({",
    `  multiTenancy: { enabled: ${answers.multiTenant} },`,
    `  email: { enabled: ${answers.emailEnabled}, provider: ${quote(answers.emailProvider)} },`,
    `  powerSync: { enabled: ${answers.mobile} },`,
    `  webhooks: { enabled: ${answers.webhooks} },`,
    `  search: { enabled: ${answers.search} },`,
    `  mcp: { enabled: ${answers.mcp} },`,
    `  fieldEncryption: { enabled: ${answers.fieldEncryption} },`,
    `  realtime: { enabled: ${answers.realtime} },`,
    "});",
    "",
  ].join("\n");
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}
